server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hims?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 65353804778
  
logging:
  level:
    com.hims: debug 